DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA VARCHAR(10) NOT NULL,
NOMBRE VARCHAR(10) NOT NULL,
APELLIDO VARCHAR(10) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT,'Pig','JORGE','PÉREZ');